# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a90501dddcff253c9d697254136d27da178b943103152142747921fadc57a19565011757727077b5c127995d77197129b03fb689113afb54488e2ba3af9491b2

test:
  secret_key_base: a41ad1fb1f791cc88ed468b8bc13c8fb337b6220139168047409d1ca6cf63a011ff0aecfe90e4ff254f8dd0895db16cbb5f51c368e46fffc48d98a76030e2db1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
